// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sequenceFieldNames          = builder.RawFieldNames(&Sequence{})
	sequenceRows                = strings.Join(sequenceFieldNames, ",")
	sequenceRowsExpectAutoSet   = strings.Join(stringx.Remove(sequenceFieldNames, "`update_time`"), ",")
	sequenceRowsWithPlaceHolder = strings.Join(stringx.Remove(sequenceFieldNames, "`biz_tag`", "`update_time`"), "=?,") + "=?"
)

type (
	sequenceModel interface {
		Insert(ctx context.Context, data *Sequence) (sql.Result, error)
		FindOne(ctx context.Context, bizTag string) (*Sequence, error)
		Update(ctx context.Context, data *Sequence) error
		Delete(ctx context.Context, bizTag string) error
	}

	defaultSequenceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Sequence struct {
		BizTag      string    `db:"biz_tag"`
		MaxId       uint64    `db:"max_id"`
		Step        uint64    `db:"step"`
		Description string    `db:"description"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newSequenceModel(conn sqlx.SqlConn) *defaultSequenceModel {
	return &defaultSequenceModel{
		conn:  conn,
		table: "`sequence`",
	}
}

func (m *defaultSequenceModel) Delete(ctx context.Context, bizTag string) error {
	query := fmt.Sprintf("delete from %s where `biz_tag` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, bizTag)
	return err
}

func (m *defaultSequenceModel) FindOne(ctx context.Context, bizTag string) (*Sequence, error) {
	query := fmt.Sprintf("select %s from %s where `biz_tag` = ? limit 1", sequenceRows, m.table)
	var resp Sequence
	err := m.conn.QueryRowCtx(ctx, &resp, query, bizTag)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSequenceModel) Insert(ctx context.Context, data *Sequence) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, sequenceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BizTag, data.MaxId, data.Step, data.Description)
	return ret, err
}

func (m *defaultSequenceModel) Update(ctx context.Context, newData *Sequence) error {
	query := fmt.Sprintf("update %s set %s where `biz_tag` = ?", m.table, sequenceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MaxId, newData.Step, newData.Description, newData.BizTag)
	return err
}

func (m *defaultSequenceModel) tableName() string {
	return m.table
}
